---
- hosts: all
  gather_facts: yes
  tasks:
    - name: Update packages list
      apt: 
        update_cache: yes
      when: (ansible_os_family == 'Debian') and (ansible_distribution_version == '11')
      become: yes
    
    - name: Upgrade packages
      apt: 
        upgrade: safe
      when: (ansible_os_family == 'Debian') and (ansible_distribution_version == '11')
      become: yes

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
      when: (ansible_os_family == 'Debian') and (ansible_distribution_version == '11')
      become: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
      when: (ansible_os_family == 'Debian') and (ansible_distribution_version == '11')
      become: yes